[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
vechain_testnet = "https://testnet.vechain.org"

[etherscan]
vechain_testnet = { key = "" } # No API key needed for Vechain
